### ISSUE TITLE
SPEED

### ISSUE THREAD

**Issue by HarveyStampyYT** [isXander/EvergreenHUD#224] opened 2022-03-19 12:45 UTC
I can not seem to be able to change my speed from m/s to MPH

![Screenshot 2022-03-19 124529](https://user-images.githubusercontent.com/101912218/159121632-8432ada1-bdab-4c9d-9a50-2775856ad7d3.png)
H

**Comment by isXander** [comment] 2022-03-19 12:49
What evergreenhud version are you using?

**Comment by HarveyStampyYT** [comment] 2022-03-19 13:25
1.18.2 Fabric

**Comment by isXander** [comment] 2022-03-19 13:39
What **EVERGREENHUD** version are you using?

**Comment by HarveyStampyYT** [comment] 2022-03-19 13:51
![image](https://user-images.githubusercontent.com/101912218/159123792-5f26c1e1-b5d8-42e4-b7bf-10451878bf7d.png)

**Comment by HarveyStampyYT** [comment] 2022-03-19 15:14
2.0.0-alpha.6

**Comment by isXander** [comment] 2022-04-27 20:41
even though this is an earlier thread, duplicate of #247

**Closed as completed by isXander** 2022-04-27 20:41 UTC
Labels: bug
